name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deploy

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build:prod

      - name: Copy index.html to 404.html
        run: cp dist/fe-student-information-system/browser/index.html dist/fe-student-information-system/browser/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/fe-student-information-system/browser
          branch: gh-pages
